#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
CONFIG_FILE="$PROJECT_ROOT/config/watchdog.conf"

# shellcheck source=/dev/null
source "$CONFIG_FILE"
export PROJECT_ROOT REPORT_DIR LOG_DIR ARCHIVE_DIR ACCESS_LOG_FILE TOP_N SUSPICIOUS_THRESHOLD TOP_IP_REPORT_FILE SUSPICIOUS_IP_REPORT_FILE BLOCKED_IP_REPORT_FILE
export BLOCK_SUSPICIOUS_IPS IPTABLES_BIN IPTABLES_CHAIN IPTABLES_DRY_RUN BLOCK_TARGET_PORTS BLOCK_REASON ALERT_ON_BLOCK
export HEALTH_URL HEALTH_TIMEOUT HEALTH_MAX_FAILURES HEALTH_LOG_FILE ALERT_EMAIL_TO ALERT_EMAIL_FROM SMTP_HOST SMTP_PORT EMAIL_ALERTS_ENABLED
export DB_ROOT CLEANUP_DAYS CLEANUP_LOG_FILE DASHBOARD_FILE FLASK_HOST FLASK_PORT METRICS_ROUTE
export REPORT_RETENTION_DAYS ARCHIVE_RETENTION_DAYS ARCHIVE_PREFIX PROMETHEUS_SCRAPE_INTERVAL PROMETHEUS_JOB_NAME

exec python3 "$PROJECT_ROOT/dashboard/app.py"
